version: '3'

services:
  api:
    build: .
    container_name: "joalheria_veronica_container"
    command: gunicorn -b 0.0.0.0:5000 -w 4 "joalheria.app:create_app()"
    ports:
      - "5000:5000"
    volumes: 
      - ".:/joalheria"
    restart: always
    environment:
      - FLASK_ENV=production
      - FLASK_APP=joalheria.app:create_app
